### ISSUE TITLE
what this is use for?

### ISSUE THREAD

**Issue by toshibochan** [mattnewham/homebridge-RFReceiver#1]
thanks for developed great plugins for homebridge.
please can you add what this plugin is for? 
i have RF Transmitter and receiver on my raspberry pi. i hoping i ca use this to receiver wireless door and window sensors to receiver notification on homekit.

**Comment by mattnewham** [comment]
Hi @toshibochan 

This project is still in development, but is working (sort of) for my application.

Currently the code exposes a motion sensor to home kit and triggers the sensor when a specific RF code is received.

If you are comfortable editing the code etc then you should be able to change it to use contact sensors.

**Comment by toshibochan** [comment]
How to configure config.json on homebridge?

**Comment by mattnewham** [comment]
Hey see the readme, I have just added more details for you :)

**Comment by toshibochan** [comment]
Cool thanks! I will try today!!

**Comment by toshibochan** [comment]
You have in npmjs.com

**Comment by toshibochan** [comment]
i getting this error:

[Sat Sep 17 2016 16:15:15 GMT-0700 (PDT)] ERROR LOADING PLUGIN homebridge-RFReceiver:
[Sat Sep 17 2016 16:15:15 GMT-0700 (PDT)] Error: Cannot find module 'rpi-433'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-RFReceiver/index.js:3:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

**Comment by toshibochan** [comment]
what this mean?
"Once you are able to run the example code from that project, and can sucessfully receive an RF code from a device, you need to put the rpi-433 code in an accesible place so that we can import the Sniffer function"

**Comment by toshibochan** [comment]
the example from https://www.npmjs.com/package/rpi-433 work fine for me.

**Comment by toshibochan** [comment]
you need run homebridge in "sudo"?

**Comment by toshibochan** [comment]
i was able to start homebridge as root and all work but homekit no give any notification. any idea way?
